globs:
    - '**/*.md'
ignores:
    - '**/node_modules'
    - '**/playwright-report'
    - './src/backstage/**'
    - './docs/**'

config:
    MD030:
        ul_multi: 3
        ul_single: 3
    MD007:
        indent: 4
