globs:
    - '**/*.md'
ignores:
    # any directory that matches
    - '**/.task-ouput'
    - '**/.wireit'
    - '**/node_modules'
    - '**/playwright-report'

    # entire sub-directories
    - './.husky/**'
    - './.vscode/**'
    - './docs/**'
    - './src/backstage/**'

config:
    MD030:
        ul_multi: 3
        ul_single: 3
    MD007:
        indent: 4
