# Ourchitecture developers use local Nexus package registries and URLs.
# However, classic Yarn versions include the registry URL in the "yarn.lock"
# lock file. So, this configuration explicitly uses the public registry to
# generate a lock file that can be shared across machines including DevOps
# pipelines.
npmRegistryServer: "https://registry.yarnpkg.com"
