apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-entity-registration-location
spec:
  type: file
  targets:
    - ./entities/groups.yaml
    - ./entities/users.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: ourstage
    description: A development experience portal.
    annotations:
      github.com/project-slug: ourchitecture/devex
      backstage.io/techdocs-ref: dir:./
spec:
    type: website
    owner: ourchitecture-maintainers
    lifecycle: experimental
