# This workflow will do a clean installation of node dependencies, cache/
# restore them, build the "ourstage" project and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: ourstage-tests

on:
    push:
        branches: ['main']
        paths:
            - '.github/workflows/ourstage-tests.yaml'
            - 'src/backstage/ourstage/**'
    pull_request:
        branches: ['main']
        paths:
            - '.github/workflows/ourstage-tests.yaml'
            - 'src/backstage/ourstage/**'

    # Enable manual triggers.
    workflow_dispatch:

env:
    CI: true
    # DEBUG: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Get npm version
              id: npm-version
              shell: bash
              run: echo "NPM_VERSION=$(cat ./.npmrc)" >> $GITHUB_OUTPUT

            - name: Get yarn version
              id: yarn-version
              shell: bash
              working-directory: ./src/backstage/ourstage/
              run: cat ./package.json | jq -r .packageManager | sed 's\yarn@\\g' | xargs -I {} -n 1 echo 'YARN_VERSION={}' >> $GITHUB_OUTPUT

            - uses: actions/setup-node@v3
              id: node-install
              with:
                  node-version-file: './.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: './src/backstage/ourstage/**/yarn.lock'

            - name: Install npm and yarn
              id: npm-and-yarn-install
              run: |
                  npm install --location=global \
                    npm@${{ steps.npm-version.outputs.NPM_VERSION }} \
                    yarn@${{ steps.yarn-version.outputs.YARN_VERSION }}

            - uses: actions/setup-python@v4
              with:
                  python-version-file: '.python-version'
                  cache: 'pip' # caching pip dependencies
                  cache-dependency-path: '**/python-requirements.txt'

            - name: Make
              id: make
              working-directory: ./src/backstage/ourstage/
              run: make
